### ISSUE TITLE
Add declarative referenced images to porter manifest

### ISSUE THREAD

**Issue by jeremyrickard** [deislabs/porter#94] opened 2018-12-09 03:05 UTC
An important part of the CNAB spec is the use of referenced images. We need to have a way to handle this with Porter. It would be _nice_ for the mixins to be able to report what they will use at bundle generation time per #70 , however in the interim we can make this a declarative feature and include it in the porter manifest.

**Comment by carolynvs** [comment] 2019-03-11 18:51
Duplicate of #70

**Closed by carolynvs** 2019-03-11 18:51 UTC
Labels: design, duplicate
