### ISSUE TITLE
Porter doesn't fix the execution bit on existing run scripts with it unset

### ISSUE THREAD

**Issue by simongdavies** [deislabs/porter#369] opened 2019-05-30 22:21 UTC
If a run script\file contained in a porter bundle definition does not have x bit set then when an action is run the invocation image will fail

---

When a user modifies the run script created by porter and unsets or otherwise loses the execution bit on the run script, porter doesn't reapply it properly.

This is a bug in how we are using [ioutil.Writefile](https://golang.org/pkg/io/ioutil/#WriteFile) during porter build. The permissions that we are applying when writing files to contents of the local cnab directory aren't being applied when the files already exist. We may have other problems with how we are using that function elsewhere.

**Comment by carolynvs** [comment] 2019-06-04 15:28
I've updated the title and OP to explain the root cause of the bug

**Comment by carolynvs** [comment] 2019-06-06 15:38
I spoke with @jeremyrickard and the fix that we agreed on is that porter should clean up intermediate build files, such as the cnab directory, at the end of build so that they don't hang around. Then before a new build, porter should delete any old generated files from a previous run before generating new ones.

**Comment by carolynvs** [comment] 2020-01-13 20:00
Closing now that we delete intermediate generated files, i.e. the .cnab directory, before building.

**Closed by carolynvs** 2020-01-13 20:00 UTC
Labels: 1 - 🍫, bug
