### ISSUE TITLE
porter mixin update command

### ISSUE THREAD

**Issue by sowsan** [deislabs/porter#848] opened 2020-01-08 19:09 UTC
A command option to update the mixins available with the current envrionment. 

E.g , the below list not up to date with the ones available in the official doc : https://porter.sh/mixins/ 
**porter mixin list**           
Name         Version          Author
aws          v0.2.0-beta.1    DeisLabs
az           v0.4.0-beta.1    DeisLabs
azure        v0.7.1-beta.1    DeisLabs
exec         v0.22.0-beta.1   DeisLabs
gcloud       v0.3.0-beta.1    DeisLabs
helm         v0.10.0-beta.1   DeisLabs
kubernetes   v0.22.0-beta.1   DeisLabs
terraform    v0.5.0-beta.1    DeisLabs

It would be great to add a command to porter mixin to update / upgrade all mixins or individual basis.
**eg.** 

**- porter mixin update --all** (update all installed mixins to latest)

**- porter mixin update -name az --version (to a specific version)**

**- porter mixin update -name az -(default to latest version)**

**Comment by carolynvs** [comment] 2020-01-08 22:33
This is great! I've added it to the backlog. 👍

**Comment by carolynvs** [comment] 2020-01-08 22:34
One more thing it should be able to do it take into account the source from where the mixin was installed, so that it can update all mixins, not just official ones.

**Comment by vdice** [comment] 2020-01-08 22:39
Good idea!  I like all of the proposed commands.  I'm thinking we should build to support `--version latest` and `--version canary` in addition to the actual semver options, e.g. `--version v0.5.0-beta.1`.

**Comment by carolynvs** [comment] 2020-01-08 23:08
Oh one more thing I just noticed is that since the other mixin commands, like `porter mixin install [NAME]` doesn't have a `-name` flag, we shouldn't have it for this one either. So it sounds like the final syntax would be this:

```
porter mixin update NAME [--version|-v VERSION]
porter mixin update --all
```

* `--version` defaults to `latest`, and also understands a semver and `canary`
* See https://github.com/deislabs/porter/issues/30#issuecomment-531493471 for the original issue and hints on how to implement

**Comment by carolynvs** [comment] 2020-01-08 23:21
Oops, since there was already an issue for `porter mixin update`, I'm going to merge your issue with that existing one and add your suggestion for `--all` to that one so we have everything in one place.

Thank you for the good idea and letting us know that you'd use the feature!

Duplicate of #30

**Closed by carolynvs** 2020-01-08 23:21 UTC
Labels: enhancement
